"""
build123d_gen.py — Build123d code generator (V2)
Converts a parsed CADModel into an executable Build123d Python script.

Uses loop_builder to order curves into continuous contours.
Polygons are emitted with Polygon(...) instead of Polyline(...) which
requires a BuildLine context. Mixed contours use a BuildLine block.
"""

from __future__ import annotations
from typing import Optional

from parser import CADModel, Sketch, Extrude, Workplane, Vec3
from loop_builder import (
    order_loop, is_closed, is_polygon,
    detect_rectangle, ordered_points, OrderedCurve,
)


# ── Plane helpers ─────────────────────────────────────────────────────────────

_B3D_PLANE_MAP = {
    "XY": "Plane.XY", "XY_neg": "Plane.XY",
    "XZ": "Plane.XZ", "XZ_neg": "Plane.XZ",
    "YZ": "Plane.YZ", "YZ_neg": "Plane.YZ",
}


def _b3d_plane(wp: Workplane) -> str:
    name = wp.plane_name
    if name and not wp.has_nonzero_origin:
        return _B3D_PLANE_MAP[name]
    o, z = wp.origin, wp.z_axis
    return (
        f"Plane("
        f"origin=({o.x*1000:.4f}, {o.y*1000:.4f}, {o.z*1000:.4f}), "
        f"z_dir=({z.x:.4f}, {z.y:.4f}, {z.z:.4f}))"
    )


# ── Arc midpoint ──────────────────────────────────────────────────────────────

def _arc_midpoint(arc: OrderedCurve) -> tuple[float, float]:
    import math
    cx, cy = arc.center
    sx, sy = arc.start
    ex, ey = arc.end
    a_start = math.atan2(sy - cy, sx - cx)
    a_end   = math.atan2(ey - cy, ex - cx)
    diff = a_end - a_start
    while diff > math.pi:
        diff -= 2 * math.pi
    while diff < -math.pi:
        diff += 2 * math.pi
    a_mid = a_start + diff / 2
    return (cx + arc.radius * math.cos(a_mid),
            cy + arc.radius * math.sin(a_mid))


# ── Loop code generation ──────────────────────────────────────────────────────

def _gen_loop_b3d(ordered: list[OrderedCurve], indent: str = "    ") -> list[str]:
    lines = []

    # Single circle
    if len(ordered) == 1 and ordered[0].is_circle:
        c = ordered[0]
        cx, cy = c.center
        if abs(cx) > 1e-6 or abs(cy) > 1e-6:
            lines.append(f"{indent}with Locations(({cx:.4f}, {cy:.4f})):")
            lines.append(f"{indent}    Circle({c.radius:.4f})")
        else:
            lines.append(f"{indent}Circle({c.radius:.4f})")
        return lines

    # Axis-aligned rectangle
    rect = detect_rectangle(ordered)
    if rect:
        cx, cy, w, h = rect
        if abs(cx) > 1e-6 or abs(cy) > 1e-6:
            lines.append(f"{indent}with Locations(({cx:.4f}, {cy:.4f})):")
            lines.append(f"{indent}    Rectangle({w:.4f}, {h:.4f})")
        else:
            lines.append(f"{indent}Rectangle({w:.4f}, {h:.4f})")
        return lines

    # Pure polygon → Polygon() (self-contained face)
    if is_polygon(ordered):
        pts = ordered_points(ordered)
        pts_str = ", ".join(f"({x:.4f}, {y:.4f})" for x, y in pts)
        lines.append(f"{indent}Polygon({pts_str})")
        return lines

    # Mixed contour → BuildLine + make_face
    lines.append(f"{indent}with BuildLine():")
    first = ordered[0]
    prev = first.start
    for seg in ordered:
        if seg.is_circle:
            continue
        if seg.kind == "line":
            lines.append(
                f"{indent}    Line(({prev[0]:.4f}, {prev[1]:.4f}), "
                f"({seg.end[0]:.4f}, {seg.end[1]:.4f}))"
            )
            prev = seg.end
        elif seg.kind == "arc":
            mx, my = _arc_midpoint(seg)
            lines.append(
                f"{indent}    ThreePointArc("
                f"({prev[0]:.4f}, {prev[1]:.4f}), "
                f"({mx:.4f}, {my:.4f}), "
                f"({seg.end[0]:.4f}, {seg.end[1]:.4f}))"
            )
            prev = seg.end
    lines.append(f"{indent}make_face()")
    return lines


# ── Mode map ──────────────────────────────────────────────────────────────────

_B3D_MODE_MAP = {
    "new_body": "Mode.ADD",
    "join":     "Mode.ADD",
    "cut":      "Mode.SUBTRACT",
    "intersect": "Mode.INTERSECT",
}


# ── Main generator ────────────────────────────────────────────────────────────

def generate(model: CADModel) -> str:
    code: list[str] = []
    code.append('"""')
    code.append(f'Build123d script generated from {model.source_file}')
    code.append('Generated by CQB123 — github.com/zoom-BT/cqb123')
    code.append('"""')
    code.append("from build123d import *")
    code.append("")

    sketch_vars: dict[str, str] = {}
    counter = 0
    for step in model.steps:
        if step.step_type == "sketch":
            counter += 1
            sketch_vars[step.entity.entity_id] = f"sketch_{counter}"

    has_solid = False

    for step in model.steps:

        if step.step_type == "sketch":
            sketch: Sketch = step.entity
            vname = sketch_vars[sketch.entity_id]
            plane_str = _b3d_plane(sketch.workplane)

            body_lines = []
            for profile in sketch.profiles.values():
                for loop in profile.loops:
                    ordered = order_loop(loop)
                    if not is_closed(ordered):
                        body_lines.append("    # WARNING: open contour skipped")
                        continue
                    body_lines.extend(_gen_loop_b3d(ordered))

            if sketch.is_orphan:
                code.append(f"# Orphan sketch '{sketch.name}' — not extruded")
                code.append(f"# with BuildSketch({plane_str}) as {vname}:")
                for bl in body_lines:
                    code.append(f"# {bl}")
                code.append("")
                continue

            code.append(f"with BuildSketch({plane_str}) as {vname}:")
            code.extend(body_lines)
            code.append("")

        elif step.step_type == "extrude":
            extrude: Extrude = step.entity
            op = extrude.operation
            mode = _B3D_MODE_MAP.get(op, "Mode.ADD")
            dist = extrude.distance_mm
            ref_ids = list(dict.fromkeys(
                r.sketch_id for r in extrude.profile_refs))

            if not has_solid:
                code.append("with BuildPart() as part:")
                has_solid = True

            for sketch_id in ref_ids:
                src = sketch_vars.get(sketch_id)
                if src is None:
                    continue
                code.append(f"    add({src}.sketch)")

            both = "both=True, " if extrude.extent_type == "two_sides" else ""
            code.append(f"    extrude(amount={dist:.4f}, {both}mode={mode})")
            code.append("")

    code.append("# Display")
    code.append("show_object(part.part)" if has_solid
                else "# No solid generated")
    return "\n".join(code)


if __name__ == "__main__":
    import sys
    from parser import parse
    if len(sys.argv) < 2:
        print("Usage: python build123d_gen.py <path_to_json>")
        sys.exit(1)
    print(generate(parse(sys.argv[1])))
