"""
cadquery_gen.py — CadQuery code generator (V2)
Converts a parsed CADModel into an executable CadQuery Python script.

Uses loop_builder to order curves into continuous contours before
emitting code, fixing the "polyline not closed" and "arc midpoint" bugs.
"""

from __future__ import annotations
from typing import Optional

from parser import CADModel, Sketch, Extrude, Workplane, Vec3
from loop_builder import (
    order_loop, is_closed, is_polygon,
    detect_rectangle, ordered_points, OrderedCurve,
)


# ── Plane helpers ─────────────────────────────────────────────────────────────

_CQ_PLANE_MAP = {
    "XY": '"XY"', "XY_neg": '"XY"',
    "XZ": '"XZ"', "XZ_neg": '"XZ"',
    "YZ": '"YZ"', "YZ_neg": '"YZ"',
}


def _cq_plane(wp: Workplane) -> str:
    name = wp.plane_name
    if name and not wp.has_nonzero_origin:
        return _CQ_PLANE_MAP[name]
    o, x, z = wp.origin, wp.x_axis, wp.z_axis
    return (
        f"cq.Plane("
        f"origin=({o.x*1000:.4f}, {o.y*1000:.4f}, {o.z*1000:.4f}), "
        f"xDir=({x.x:.4f}, {x.y:.4f}, {x.z:.4f}), "
        f"normal=({z.x:.4f}, {z.y:.4f}, {z.z:.4f}))"
    )


# ── Arc midpoint ──────────────────────────────────────────────────────────────

def _arc_midpoint(arc: OrderedCurve) -> tuple[float, float]:
    """Correct point ON the arc, halfway between start and end."""
    import math
    cx, cy = arc.center
    sx, sy = arc.start
    ex, ey = arc.end
    a_start = math.atan2(sy - cy, sx - cx)
    a_end   = math.atan2(ey - cy, ex - cx)
    diff = a_end - a_start
    while diff > math.pi:
        diff -= 2 * math.pi
    while diff < -math.pi:
        diff += 2 * math.pi
    a_mid = a_start + diff / 2
    return (cx + arc.radius * math.cos(a_mid),
            cy + arc.radius * math.sin(a_mid))


# ── Loop code generation ──────────────────────────────────────────────────────

def _gen_loop_cq(ordered: list[OrderedCurve]) -> list[str]:
    lines = []

    # Single circle
    if len(ordered) == 1 and ordered[0].is_circle:
        c = ordered[0]
        cx, cy = c.center
        if abs(cx) > 1e-6 or abs(cy) > 1e-6:
            lines.append(f"    .moveTo({cx:.4f}, {cy:.4f})")
        lines.append(f"    .circle({c.radius:.4f})")
        return lines

    # Axis-aligned rectangle
    rect = detect_rectangle(ordered)
    if rect:
        cx, cy, w, h = rect
        if abs(cx) > 1e-6 or abs(cy) > 1e-6:
            lines.append(f"    .moveTo({cx:.4f}, {cy:.4f})")
        lines.append(f"    .rect({w:.4f}, {h:.4f})")
        return lines

    # Pure polygon
    if is_polygon(ordered):
        pts = ordered_points(ordered)
        pts_closed = pts + [pts[0]]
        pts_str = ", ".join(f"({x:.4f}, {y:.4f})" for x, y in pts_closed)
        lines.append(f"    .polyline([{pts_str}]).close()")
        return lines

    # Mixed contour (lines + arcs)
    first = ordered[0]
    lines.append(f"    .moveTo({first.start[0]:.4f}, {first.start[1]:.4f})")
    for seg in ordered:
        if seg.is_circle:
            continue
        if seg.kind == "line":
            lines.append(f"    .lineTo({seg.end[0]:.4f}, {seg.end[1]:.4f})")
        elif seg.kind == "arc":
            mx, my = _arc_midpoint(seg)
            lines.append(
                f"    .threePointArc(({mx:.4f}, {my:.4f}), "
                f"({seg.end[0]:.4f}, {seg.end[1]:.4f}))"
            )
    lines.append(f"    .close()")
    return lines


# ── Main generator ────────────────────────────────────────────────────────────

def generate(model: CADModel) -> str:
    code: list[str] = []
    code.append('"""')
    code.append(f'CadQuery script generated from {model.source_file}')
    code.append('Generated by CQB123 — github.com/zoom-BT/cqb123')
    code.append('"""')
    code.append("import cadquery as cq")
    code.append("")

    sketch_vars: dict[str, str] = {}
    counter = 0
    for step in model.steps:
        if step.step_type == "sketch":
            counter += 1
            sketch_vars[step.entity.entity_id] = f"sketch_{counter}"

    has_solid = False
    result_var = "result"

    for step in model.steps:

        if step.step_type == "sketch":
            sketch: Sketch = step.entity
            vname = sketch_vars[sketch.entity_id]
            plane_str = _cq_plane(sketch.workplane)

            body_lines = []
            for profile in sketch.profiles.values():
                for loop in profile.loops:
                    ordered = order_loop(loop)
                    if not is_closed(ordered):
                        body_lines.append("    # WARNING: open contour skipped")
                        continue
                    body_lines.extend(_gen_loop_cq(ordered))

            if sketch.is_orphan:
                code.append(f"# Orphan sketch '{sketch.name}' — not extruded")
                code.append(f"# {vname} = (")
                code.append(f"#     cq.Workplane({plane_str})")
                for bl in body_lines:
                    code.append(f"# {bl}")
                code.append("# )")
                code.append("")
                continue

            code.append(f"{vname} = (")
            code.append(f"    cq.Workplane({plane_str})")
            code.extend(body_lines)
            code.append(")")
            code.append("")

        elif step.step_type == "extrude":
            extrude: Extrude = step.entity
            op = extrude.operation
            dist = extrude.distance_mm
            ref_ids = list(dict.fromkeys(
                r.sketch_id for r in extrude.profile_refs))
            both = ", both=True" if extrude.extent_type == "two_sides" else ""

            for sketch_id in ref_ids:
                src = sketch_vars.get(sketch_id)
                if src is None:
                    continue

                if not has_solid and op == "new_body":
                    code.append(f"{result_var} = (")
                    code.append(f"    {src}")
                    code.append(f"    .extrude({dist:.4f}{both})")
                    code.append(")")
                    has_solid = True
                elif op == "cut" and has_solid:
                    code.append(f"{result_var} = {result_var}.cut("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif op in ("join", "new_body") and has_solid:
                    code.append(f"{result_var} = {result_var}.union("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif op == "intersect" and has_solid:
                    code.append(f"{result_var} = {result_var}.intersect("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif not has_solid:
                    # First solid even if not new_body
                    code.append(f"{result_var} = (")
                    code.append(f"    {src}")
                    code.append(f"    .extrude({dist:.4f}{both})")
                    code.append(")")
                    has_solid = True
                code.append("")

    code.append("# Display")
    code.append(f"show_object({result_var})" if has_solid
                else "# No solid generated")
    return "\n".join(code)


if __name__ == "__main__":
    import sys
    from parser import parse
    if len(sys.argv) < 2:
        print("Usage: python cadquery_gen.py <path_to_json>")
        sys.exit(1)
    print(generate(parse(sys.argv[1])))
