"""
cadquery_gen.py — CadQuery code generator (V2)
Converts a parsed CADModel into an executable CadQuery Python script.

Uses loop_builder to order curves into continuous contours before
emitting code, fixing the "polyline not closed" and "arc midpoint" bugs.
"""

from __future__ import annotations
from typing import Optional

from parser import CADModel, Sketch, Extrude, Workplane, Vec3
from loop_builder import (
    order_loop, is_closed, is_polygon,
    detect_rectangle, ordered_points, OrderedCurve,
    classify_loops,
)


# ── Plane helpers ─────────────────────────────────────────────────────────────

_CQ_PLANE_MAP = {
    "XY": '"XY"', "XY_neg": '"XY"',
    "XZ": '"XZ"', "XZ_neg": '"XZ"',
    "YZ": '"YZ"', "YZ_neg": '"YZ"',
}


def _cq_plane(wp: Workplane) -> str:
    name = wp.plane_name
    if name and not wp.has_nonzero_origin:
        return _CQ_PLANE_MAP[name]
    o, x, z = wp.origin, wp.x_axis, wp.z_axis
    return (
        f"cq.Plane("
        f"origin=({o.x*1000:.4f}, {o.y*1000:.4f}, {o.z*1000:.4f}), "
        f"xDir=({x.x:.4f}, {x.y:.4f}, {x.z:.4f}), "
        f"normal=({z.x:.4f}, {z.y:.4f}, {z.z:.4f}))"
    )


# ── Arc midpoint ──────────────────────────────────────────────────────────────

def _arc_midpoint(arc: OrderedCurve) -> tuple[float, float]:
    """Correct point ON the arc, halfway between start and end."""
    import math
    cx, cy = arc.center
    sx, sy = arc.start
    ex, ey = arc.end
    a_start = math.atan2(sy - cy, sx - cx)
    a_end   = math.atan2(ey - cy, ex - cx)
    diff = a_end - a_start
    while diff > math.pi:
        diff -= 2 * math.pi
    while diff < -math.pi:
        diff += 2 * math.pi
    a_mid = a_start + diff / 2
    return (cx + arc.radius * math.cos(a_mid),
            cy + arc.radius * math.sin(a_mid))


# ── Loop code generation ──────────────────────────────────────────────────────

def _gen_single_loop(ordered: list[OrderedCurve], plane_str: str) -> str:
    """
    Build ONE closed contour as a complete cq.Workplane(...) expression.
    Returns a single-line (or multi-line) expression string.
    Each contour is self-contained so multiple contours never collide.
    """
    # Single circle
    if len(ordered) == 1 and ordered[0].is_circle:
        c = ordered[0]
        cx, cy = c.center
        move = f".moveTo({cx:.4f}, {cy:.4f})" if (abs(cx) > 1e-6 or abs(cy) > 1e-6) else ""
        return f"cq.Workplane({plane_str}){move}.circle({c.radius:.4f})"

    # Rectangle
    rect = detect_rectangle(ordered)
    if rect:
        cx, cy, w, h = rect
        move = f".moveTo({cx:.4f}, {cy:.4f})" if (abs(cx) > 1e-6 or abs(cy) > 1e-6) else ""
        return f"cq.Workplane({plane_str}){move}.rect({w:.4f}, {h:.4f})"

    # Pure polygon
    if is_polygon(ordered):
        pts = ordered_points(ordered)
        pts_closed = pts + [pts[0]]
        pts_str = ", ".join(f"({x:.4f}, {y:.4f})" for x, y in pts_closed)
        return f"cq.Workplane({plane_str}).polyline([{pts_str}]).close()"

    # Mixed contour (lines + arcs)
    parts = [f"cq.Workplane({plane_str})"]
    first = ordered[0]
    parts.append(f".moveTo({first.start[0]:.4f}, {first.start[1]:.4f})")
    for seg in ordered:
        if seg.is_circle:
            continue
        if seg.kind == "line":
            parts.append(f".lineTo({seg.end[0]:.4f}, {seg.end[1]:.4f})")
        elif seg.kind == "arc":
            mx, my = _arc_midpoint(seg)
            parts.append(
                f".threePointArc(({mx:.4f}, {my:.4f}), "
                f"({seg.end[0]:.4f}, {seg.end[1]:.4f}))"
            )
    parts.append(".close()")
    return "".join(parts)


# ── Main generator ────────────────────────────────────────────────────────────

def generate(model: CADModel) -> str:
    code: list[str] = []
    code.append('"""')
    code.append(f'CadQuery script generated from {model.source_file}')
    code.append('Generated by CQB123 — github.com/zoom-BT/cqb123')
    code.append('"""')
    code.append("import cadquery as cq")
    code.append("")

    sketch_vars: dict[str, str] = {}
    counter = 0
    for step in model.steps:
        if step.step_type == "sketch":
            counter += 1
            sketch_vars[step.entity.entity_id] = f"sketch_{counter}"

    has_solid = False
    result_var = "result"
    sketch_holes: dict[str, list] = {}

    for step in model.steps:

        if step.step_type == "sketch":
            sketch: Sketch = step.entity
            vname = sketch_vars[sketch.entity_id]
            plane_str = _cq_plane(sketch.workplane)

            # Classify all loops globally (best empirical equivalence rate)
            all_ordered = []
            for profile in sketch.profiles.values():
                for loop in profile.loops:
                    ordered = order_loop(loop)
                    if is_closed(ordered):
                        all_ordered.append(ordered)
            classified = classify_loops(all_ordered) if all_ordered else []
            solids = [c["contour"] for c in classified if not c["is_hole"]]
            holes  = [c["contour"] for c in classified if c["is_hole"]]

            solid_exprs = [_gen_single_loop(o, plane_str) for o in solids]
            hole_exprs  = [_gen_single_loop(o, plane_str) for o in holes]

            if not solid_exprs:
                solid_exprs = [f"cq.Workplane({plane_str})"]

            if sketch.is_orphan:
                code.append(f"# Orphan sketch '{sketch.name}' — not extruded")
                code.append(f"# {vname} = {solid_exprs[0]}")
                code.append("")
                # store empty hole list
                sketch_holes[sketch.entity_id] = []
                continue

            # Combine solid contours
            if len(solid_exprs) == 1:
                code.append(f"{vname} = {solid_exprs[0]}")
            else:
                code.append(f"{vname} = (")
                code.append(f"    {solid_exprs[0]}")
                for expr in solid_exprs[1:]:
                    code.append(f"    .add({expr})")
                code.append(")")

            # Store hole expressions for the extrude step to cut
            sketch_holes[sketch.entity_id] = hole_exprs
            if hole_exprs:
                hvar = f"{vname}_holes"
                if len(hole_exprs) == 1:
                    code.append(f"{hvar} = {hole_exprs[0]}")
                else:
                    code.append(f"{hvar} = (")
                    code.append(f"    {hole_exprs[0]}")
                    for expr in hole_exprs[1:]:
                        code.append(f"    .add({expr})")
                    code.append(")")
            code.append("")

        elif step.step_type == "extrude":
            extrude: Extrude = step.entity
            op = extrude.operation
            dist = extrude.distance_mm
            ref_ids = list(dict.fromkeys(
                r.sketch_id for r in extrude.profile_refs))
            both = ", both=True" if extrude.extent_type == "two_sides" else ""

            for sketch_id in ref_ids:
                src = sketch_vars.get(sketch_id)
                if src is None:
                    continue

                has_holes = bool(sketch_holes.get(sketch_id))
                hvar = f"{src}_holes"

                if not has_solid and op == "new_body":
                    code.append(f"{result_var} = (")
                    code.append(f"    {src}")
                    code.append(f"    .extrude({dist:.4f}{both})")
                    code.append(")")
                    has_solid = True
                elif op == "cut" and has_solid:
                    code.append(f"{result_var} = {result_var}.cut("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif op in ("join", "new_body") and has_solid:
                    code.append(f"{result_var} = {result_var}.union("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif op == "intersect" and has_solid:
                    code.append(f"{result_var} = {result_var}.intersect("
                                f"{src}.extrude({dist:.4f}{both}))")
                elif not has_solid:
                    code.append(f"{result_var} = (")
                    code.append(f"    {src}")
                    code.append(f"    .extrude({dist:.4f}{both})")
                    code.append(")")
                    has_solid = True

                # Cut any holes belonging to this sketch
                if has_holes and op != "cut":
                    code.append(f"{result_var} = {result_var}.cut("
                                f"{hvar}.extrude({dist:.4f}{both}))")
                code.append("")

    code.append("# Display")
    code.append(f"show_object({result_var})" if has_solid
                else "# No solid generated")
    return "\n".join(code)


if __name__ == "__main__":
    import sys
    from parser import parse
    if len(sys.argv) < 2:
        print("Usage: python cadquery_gen.py <path_to_json>")
        sys.exit(1)
    print(generate(parse(sys.argv[1])))
